# Generated by Django 5.0 on 2024-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileimages",
            name="cover_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofileimages",
            name="profile_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
