# Generated by Django 5.0 on 2023-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('department_id', models.CharField(blank=True, max_length=250, null=True)),
                ('total_teachers', models.CharField(blank=True, max_length=250, null=True)),
                ('total_students', models.CharField(blank=True, max_length=250, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
