# Generated by Django 5.0 on 2024-01-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department_images'),
        ),
    ]
