# Generated by Django 5.0 on 2024-01-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='department_id',
        ),
    ]
